name: Build & Release Docker Image

on:
  push:
    branches: [main] # always update :latest from main
    tags: ["v*.*.*"] # e.g. v2.0.1 -> push :2.0.1 (+ latest)

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: flengure/mcp-prompt-loader

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Detect context (main vs tag)
        id: meta
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
            echo "mode=tag" >> "$GITHUB_OUTPUT"
            echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          else
            echo "mode=main" >> "$GITHUB_OUTPUT"
          fi

      # --- Push :latest on any push to main (multi-arch) ---
      - name: Build & push :latest (main)
        if: steps.meta.outputs.mode == 'main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest

      # --- Push :<version> and :latest on tag (multi-arch) ---
      - name: Build & push :<version> and :latest (tag)
        if: steps.meta.outputs.mode == 'tag'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
            ${{ env.IMAGE_NAME }}:latest
